### ISSUE TITLE
Adding prettier configuration

### ISSUE THREAD

**Issue by flashblaze** [arpitbatra123/betterreads#3]
Are you open to adding prettier config to project by extending it via [eslint-prettier-config](https://github.com/prettier/eslint-config-prettier)?

**Comment by arpitbatra123** [comment]
Yes, That'll be great! Please go ahead and create a PR! If you could also enable lint on commit using a GitHub action, then that can be a cherry on top!

**Comment by flashblaze** [comment]
Sure. I'll look into it.
